server:
  port: 8081
  servlet:
    encoding:
      force: true
spring:
  config:
    activate:
      on-profile: @profile.active@
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jianmu?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    out-of-order: false
    validate-on-migrate: true
    encoding: UTF-8
  jackson:
    parser:
      ALLOW_UNQUOTED_CONTROL_CHARS: true

pagehelper:
  support-methods-arguments: true
logging:
  charset:
    console: UTF-8

grpc:
  server:
    port: 5001
  client:
    GLOBAL:
      address: static://127.0.0.1:5001
      negotiation-type: plaintext

storage:
  logfile-path: task_log
embedded:
  docker-worker:
    docker-host: tcp://127.0.0.1:2375
    api-version: v1.39
json:
  repository:
    repo-path: task_def
jianmu:
  api:
    jwtSecret: Hahhahhhaahh
    jwtExpirationMs: 86400000
    adminPasswd: 123456
